#!/usr/bin/env python
import os
import argparse
from bucoffea.helpers.merging import CoffeaMerger


def parse_commandline():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "indir",
        type=str,
        help="The input directory holding the coffea files to be merged.",
    )
    parser.add_argument(
        "--jobs",
        "-j",
        type=int,
        default=1,
        help="The number of cores to use for merging.",
    )
    parser.add_argument(
        "--outdir",
        "-o",
        type=str,
        default=None,
        help="The output directory to use.",
    )

    args = parser.parse_args()
    
    # Default name of the output directory
    if not args.outdir:
        input_dir = os.path.basename(os.path.abspath(args.indir))
        args.outdir = f'merged_{input_dir}'

    return args


def main():
    args = parse_commandline()
    print(f'Merging and saving to output directory: {args.outdir}')
    
    cm = CoffeaMerger(indir=args.indir, jobs=args.jobs)
    cm.to_klepto_dir(args.outdir)


if __name__ == "__main__":
    main()
